export const NODE_PROCESS = "ep8rWZk9Kr5NkUZDWLcKoDw9TuRgK3rBkDAyJrn98Tc"
export const TASK_PROCESS = "KapcJCEKKLghKIXUqcb2qWHjl_KQKfJwGCFEIkQ9Y0M"
// export const TOKEN_PROCESS = "aS_u_cfbXGgOE7IzEqj85a0ok6zNclTUzRSTjNuL5wE"
export const TOKEN_PROCESS = "Sa0iBLPNyJQrwpTTG-tWLQU-1QeUAJA73DdxGGiKoJc"
export const DATA_PROCESS = "iXFZUCEcrXYGn85losNyzuKWmZ9fxx-YxqitsHqqkz8"
